In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("./dubai_cold_coffee_spots_clean.csv")

In [3]:
df.shape

(50, 7)

In [4]:
df

,name,lat,lng,type,rating,opening_time,closing_time
0,Brewed Awakening,25.207773,55.290559,cart,4.3,09:00,23:00
1,Chill & Spill,25.248509,55.301298,truck,4.7,08:00,20:00
2,Frosty Mug,25.152942,55.295840,cafe,4.9,06:00,21:00
3,Caffeine Cartel,25.217613,55.346531,cart,3.7,10:00,23:00
4,The Bean Scene,25.154320,55.340818,cafe,4.9,10:00,20:00
5,Cool Beans,25.192334,55.263833,cafe,4.8,09:00,21:00
6,Espresso Express,25.178230,55.256539,cart,4.9,09:00,20:00
7,Mocha Motion,25.159676,55.337032,truck,4.2,08:00,23:00
8,Frozen Grind,25.191297,55.335197,cart,4.1,06:00,23:00
9,Perk Up Cafe,25.246448,55.272767,cart,4.3,06:00,22:00
10,The Daily Brew,25.233261,55.330552,cart,4.0,06:00,21:00
11,Latte on the Go,25.248106,55.304331,cart,3.5,10:00,20:00
12,Bean There,25.179933,55.326601,cafe,4.2,08:00,20:00
13,Sip Stop,25.200194,55.297612,cart,4.6,08:00,22:00
14,Iced & Easy,25.170497,55.311298,cafe,3.6,09:00,23:00
15,Grind House,25.203164,55.304382,cart,4.6,09:00,21:00
16,Arctic Brew,25.228260,55.281833,cart,4.8,09:00,22:00
17,Quick Drip,25.243381,55.312097,cart,3.6,07:00,22:00
18,Mug Life,25.220186,55.289355,truck,3.5,07:00,21:00
19,Flat White Truck,25.179104,55.348576,cart,3.9,09:00,23:00
20,Brrrista,25.173272,55.252322,cafe,4.0,06:00,23:00
21,Chai Chiller,25.218065,55.269152,cafe,4.4,06:00,23:00
22,Caffeinated Camel,25.191213,55.269632,cart,4.7,09:00,20:00
23,Desert Drip,25.161236,55.259174,cafe,3.8,06:00,23:00
24,Java Oasis,25.159588,55.305825,cart,4.5,10:00,23:00
25,Frost & Found,25.190576,55.336748,truck,4.6,10:00,17:00
26,Shake Shack Cafe,25.239039,55.307756,cart,3.7,06:00,23:00
27,Cooler Beans,25.212366,55.269280,cart,5.0,06:00,21:00
28,Nomad Brew,25.239391,55.306152,truck,4.9,09:00,21:00
29,Pulse Cafe,25.182038,55.336626,cart,4.4,09:00,20:00
30,Buzz Station,25.201734,55.318113,cart,4.4,07:00,22:00
31,Bean Bazaar,25.198350,55.305205,truck,4.9,08:00,23:00
32,Sippin’ Point,25.244079,55.331386,cart,4.4,08:00,20:00
33,The Ice Press,25.191494,55.314447,cafe,4.9,09:00,20:00
34,The Chill Spot,25.209224,55.304276,cafe,4.8,06:00,23:00
35,Velvet Roast,25.186886,55.348506,cafe,3.7,08:00,17:00
36,Cafe Mirage,25.166434,55.319951,cart,3.6,09:00,22:00
37,Iced Rush,25.172374,55.271237,truck,4.9,06:00,21:00
38,Snowy Shot,25.230627,55.265882,truck,4.8,06:00,21:00
39,Café Breeze,25.150536,55.338752,cafe,4.5,07:00,22:00
40,Route 66 Coffee,25.216620,55.342005,cart,4.4,06:00,20:00
41,Shot Stop,25.235518,55.250343,cafe,5.0,08:00,22:00
42,Steamy vs Icy,25.213372,55.344224,cafe,3.8,08:00,23:00
43,Latte Land,25.154616,55.309822,cafe,4.1,07:00,22:00
44,Cold Culture,25.248168,55.327985,cafe,4.7,09:00,17:00
45,Brewie Louie,25.245210,55.253333,cafe,4.0,09:00,23:00
46,The Roasted Route,25.180392,55.254501,cafe,4.3,08:00,23:00
47,Carafe Cart,25.199326,55.346555,truck,4.5,06:00,21:00
48,Frozen Feels,25.173230,55.280982,truck,4.7,08:00,23:00
49,Iced Daily,25.213998,55.275438,cart,4.1,08:00,23:00

In [5]:
df_areas = pd.read_csv("./dubai_areas.csv")

In [6]:
df_areas

            area_name emoji     lat     lng
0      Downtown Dubai    🏙️  25.200  55.300
1      Jumeirah Beach     🌊  25.205  55.260
2        Business Bay     🏢  25.185  55.310
3           City Walk    🛍️  25.210  55.270
4             Al Safa     🕌  25.175  55.255
5   Sheikh Zayed Road     🌆  25.220  55.290
6                DIFC     🏨  25.215  55.285
7         Zabeel Park     🌳  25.230  55.320
8             Al Wasl     🏫  25.190  55.340
9           Oud Metha     🏪  25.240  55.315
10        Al Jafiliya     🚇  25.245  55.295
11        Al Mankhool    🏘️  25.165  55.305
12            Al Bada     🌴  25.155  55.330
13              Satwa     🏬  25.175  55.275

In [7]:
df_areas["label"] = df_areas["emoji"] + " " + df_areas["area_name"]

In [8]:
df_areas

            area_name emoji     lat     lng                label
0      Downtown Dubai    🏙️  25.200  55.300    🏙️ Downtown Dubai
1      Jumeirah Beach     🌊  25.205  55.260     🌊 Jumeirah Beach
2        Business Bay     🏢  25.185  55.310       🏢 Business Bay
3           City Walk    🛍️  25.210  55.270         🛍️ City Walk
4             Al Safa     🕌  25.175  55.255            🕌 Al Safa
5   Sheikh Zayed Road     🌆  25.220  55.290  🌆 Sheikh Zayed Road
6                DIFC     🏨  25.215  55.285               🏨 DIFC
7         Zabeel Park     🌳  25.230  55.320        🌳 Zabeel Park
8             Al Wasl     🏫  25.190  55.340            🏫 Al Wasl
9           Oud Metha     🏪  25.240  55.315          🏪 Oud Metha
10        Al Jafiliya     🚇  25.245  55.295        🚇 Al Jafiliya
11        Al Mankhool    🏘️  25.165  55.305       🏘️ Al Mankhool
12            Al Bada     🌴  25.155  55.330            🌴 Al Bada
13              Satwa     🏬  25.175  55.275              🏬 Satwa

In [9]:
df_areas.to_csv("dubai_areas_label.csv")

In [10]:
aa = list(df_areas["label"])

In [11]:
aa.insert(0,"select..")

In [12]:
aa

['select..',
 '🏙️ Downtown Dubai',
 '🌊 Jumeirah Beach',
 '🏢 Business Bay',
 '🛍️ City Walk',
 '🕌 Al Safa',
 '🌆 Sheikh Zayed Road',
 '🏨 DIFC',
 '🌳 Zabeel Park',
 '🏫 Al Wasl',
 '🏪 Oud Metha',
 '🚇 Al Jafiliya',
 '🏘️ Al Mankhool',
 '🌴 Al Bada',
 '🏬 Satwa']

In [13]:
df[df["type"]=="cafe"]

,name,lat,lng,type,rating,opening_time,closing_time
2,Frosty Mug,25.152942,55.295840,cafe,4.9,06:00,21:00
4,The Bean Scene,25.154320,55.340818,cafe,4.9,10:00,20:00
5,Cool Beans,25.192334,55.263833,cafe,4.8,09:00,21:00
12,Bean There,25.179933,55.326601,cafe,4.2,08:00,20:00
14,Iced & Easy,25.170497,55.311298,cafe,3.6,09:00,23:00
20,Brrrista,25.173272,55.252322,cafe,4.0,06:00,23:00
21,Chai Chiller,25.218065,55.269152,cafe,4.4,06:00,23:00
23,Desert Drip,25.161236,55.259174,cafe,3.8,06:00,23:00
33,The Ice Press,25.191494,55.314447,cafe,4.9,09:00,20:00
34,The Chill Spot,25.209224,55.304276,cafe,4.8,06:00,23:00
35,Velvet Roast,25.186886,55.348506,cafe,3.7,08:00,17:00
39,Café Breeze,25.150536,55.338752,cafe,4.5,07:00,22:00
41,Shot Stop,25.235518,55.250343,cafe,5.0,08:00,22:00
42,Steamy vs Icy,25.213372,55.344224,cafe,3.8,08:00,23:00
43,Latte Land,25.154616,55.309822,cafe,4.1,07:00,22:00
44,Cold Culture,25.248168,55.327985,cafe,4.7,09:00,17:00
45,Brewie Louie,25.245210,55.253333,cafe,4.0,09:00,23:00
46,The Roasted Route,25.180392,55.254501,cafe,4.3,08:00,23:00

In [14]:
%pip install geopy

Requirement already satisfied: geopy in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (2.4.1)
Requirement already satisfied: geographiclib<3,>=1.52 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from geopy) (2.1)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python3 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [15]:
from geopy.distance import geodesic
user_location=(25.240,55.315)
spot_location=(25.165,55.305)
geodesic(user_location,spot_location).km

8.369098927185167

In [16]:
def calculate_distance(row):
    lat = row["lat"]
    lng = row["lng"]
    spot_location =(lat,lng)
    dis= geodesic(user_location,spot_location).km
    return round(dis,2)
df["distance_km"] =df.apply(calculate_distance,axis=1)

In [17]:
from datetime import datetime
datetime.now().strftime("%H:%M")

'18:14'

In [18]:
def is_open(row):
    current_time= datetime.now().strftime("%H:%M")
    open_time=row["opening_time"]
    close_time=row["closing_time"]
    if open_time <= current_time <= close_time:
        return "open"
    else:
        return "closed"

In [19]:
rows=df.iloc[0:2]
for ind,row in rows.iterrows():
    print(row["name"],row["type"],row["distance_km"])

Brewed Awakening cart 4.34
Chill & Spill truck 1.67